/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_moliso_shelxle_FourXle */

#ifndef _Included_de_moliso_shelxle_FourXle
#define _Included_de_moliso_shelxle_FourXle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_moliso_shelxle_FourXle
 * Method:    loadFouAndPerform
 * Signature: (Ljava/lang/String;Z[F[F[F)Z
 */
JNIEXPORT jfloatArray JNICALL Java_de_moliso_shelxle_FourXle_loadFouAndPerform
  (JNIEnv *, jobject, jstring, jboolean,  jfloatArray);
/*
 * Class:     de_moliso_shelxle_FourXle
 * Method:    getFoPlus
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_moliso_shelxle_FourXle_getFoPlus
  (JNIEnv *, jobject);

/*
 * Class:     de_moliso_shelxle_FourXle
 * Method:    getFoMinus
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_moliso_shelxle_FourXle_getFoMinus
  (JNIEnv *, jobject);

/*
 * Class:     de_moliso_shelxle_FourXle
 * Method:    getDifPlus
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_moliso_shelxle_FourXle_getDifPlus
  (JNIEnv *, jobject);

/*
 * Class:     de_moliso_shelxle_FourXle
 * Method:    getDifMinus
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_moliso_shelxle_FourXle_getDifMinus
  (JNIEnv *, jobject);

/*
 * Class:     de_moliso_shelxle_FourXle
 * Method:    change_iso
 * Signature: (II[F[F[F)V
 */
JNIEXPORT void JNICALL Java_de_moliso_shelxle_FourXle_change_1iso
  (JNIEnv *, jobject, jint, jint, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
